telegram_content_scrapper/config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("telegram_content_scrapper.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("telegram/", include("telegram_content_scrapper.telegram_scrapper.urls")),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

telegram_content_scrapper/telegram_content_scrapper/telegram_scrapper/urls.py
from django.urls import path
# from .views import 
from telegram_content_scrapper.telegram_scrapper.views import telegram_user_authentication_view, user_telegram_entities_view, get_telegram_otp_code, fetch_telegram_entity_contents,update_telegram_entity_contents, assign_telegram_entity_contents_fetching_task

app_name = "telegram"

urlpatterns = [
    path("contents/", view=user_telegram_entities_view, name="contents"),
    path("api/entity/contents/", fetch_telegram_entity_contents, name="get-contents"),
    path("api/task/contents/", assign_telegram_entity_contents_fetching_task, name="contents-fetching"),
    path("api/entity/contents/update", update_telegram_entity_contents, name="update-content"),
    path("authentication/", view=telegram_user_authentication_view, name="authentication"),
    path("api/auth/send-otp/", get_telegram_otp_code, name="send-otp"),
]

telegram_content_scrapper/telegram_content_scrapper/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view
from .views import logout_delete_cookie_data

app_name = "users"
urlpatterns = [
    path("logout/", logout_delete_cookie_data, name="logout"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

telegram_content_scrapper/telegram_content_scrapper/telegram_scrapper/forms.py
from django import forms

class TelegramAuthenticationForm(forms.Form):
    code = forms.CharField(label="OTP Code",widget=forms.TextInput(
            attrs={"placeholder": "Enter OTP Code", "autocomplete": "off", "class": "w-50 text-center form-control"}
        ),)

telegram_content_scrapper/telegram_content_scrapper/telegram_scrapper/views.py
from datetime import timedelta, datetime
import json
import os
import sys
from django.shortcuts import render, redirect
from django.utils import timezone

# Create your views here.

from django.views import View
from django.views.generic.base import TemplateView
# from telegram_content_scrapper.telegram_scrapper.models import TelegramEntityInfo
from django.http import JsonResponse
from django.conf import settings
from .dummy_test_data import DATA
from telegram_content_scrapper.telegram_scrapper.forms import TelegramAuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .telethon_funcs import telethon_send_code_request, session_validation, telethon_user_entities, telethon_verification_code_sign_in
from asgiref.sync import sync_to_async, async_to_sync
from .models import TelethonSession, TelegramUserEntity, TelegramEntityContentData
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .tasks import load_user_telegram_entities, load_user_telegram_entity_contents
from celery.result import AsyncResult


DEFAULT_PER_FETCH = 1000

class UserTelegramEntitiesView(TemplateView):
    template_name = 'telegram_scrapper/telegram_entities_list.html'

    # Session Data in Browser Cookie storage
    def get(self, request, *args, **kwargs):
        try:
            user_id = request.user.id
            username = request.user.username
            phone_number_object = request.user.telegram_phone_number
            if phone_number_object is not None:
              telegram_phone_number = phone_number_object.as_e164
              load_user_telegram_session_data_str = request.COOKIES.get(f"{username}{telegram_phone_number}")
              if load_user_telegram_session_data_str is not None:
                  load_user_telegram_session_data = json.loads(load_user_telegram_session_data_str)
                  telegram_phone_hash = load_user_telegram_session_data.get("telegram_phone_hash")
                  telegram_session_str = load_user_telegram_session_data.get("telegram_session_str")
                  if telegram_session_str is not None:
                      data_returning = async_to_sync(session_validation)(telegram_session_str.encode())
                      _is_valid_session = data_returning.get("is_valid")
                      if _is_valid_session:
                          # update the user's latest telegram entities info in the background
                          load_user_telegram_entities.delay(user_id,telegram_session_str.encode())

                          # pull the current available user telegram entities info from database
                          user_entities_data = TelegramUserEntity.objects.filter(user_id=user_id, is_still_linked=True)
                          entities_types = []
                          entities_list = []
                          for user_entity in user_entities_data:
                              entity_info = user_entity.telegram_entity
                              entities_list.append(
                                  {
                                      "entity_id": entity_info.id,
                                      "entity_name": entity_info.entity_name,
                                      "entity_type": entity_info.entity_type,
                                  }
                              )
                          if len(entities_list):
                              entities_types = list(set(e.get("entity_type") for e in entities_list))
                          content = {
                              "entities_types": entities_types,
                              "options": entities_list
                          }
                          response = render(request, self.template_name, content)
                          response.set_cookie(
                              f"{username}{telegram_phone_number}",
                              load_user_telegram_session_data_str,
                              httponly=True,  # Prevent JavaScript access
                              # secure=True,  # Send only over HTTPS
                              samesite="Strict",  # Prevent CSRF attacks
                              max_age=432000  # set session age for 5 days
                          )
                          return response
            # any else got redirect to authentication
            return redirect('telegram:authentication')
        except Exception as e:
            exc_type, exc_obj, exc_tb = sys.exc_info()
            fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
            print(exc_type, fname, exc_tb.tb_lineno)
            _error = f"error - {e}"
            return render(request, "500.html", context={"exception": f"Error - {_error}"})


    # NOTE: session_data in database
    # def get(self, request, *args, **kwargs):
    #     try:
    #         user_id = request.user.id
    #         phone_number_object = request.user.telegram_phone_number
    #         _user_telegram_session = TelethonSession.objects.filter(owner_id=user_id, phone_number=phone_number_object).first()
    #         if _user_telegram_session is not None:
    #             _is_verified = _user_telegram_session.is_verified
    #             if _is_verified:
    #                 _session_data = _user_telegram_session.session_data
    #                 data_returning = async_to_sync(session_validation)(_session_data)
    #                 _is_valid_session = data_returning.get("is_valid")
    #                 if _is_valid_session:
    #                     # update the user's latest telegram entities info in the background
    #                     load_user_telegram_entities.delay(user_id,_session_data)

    #                     # pull the current available user telegram entities info from database
    #                     user_entities_data = TelegramUserEntity.objects.filter(user_id=user_id, is_still_linked=True)
    #                     entities_types = []
    #                     entities_list = []
    #                     for user_entity in user_entities_data:
    #                         entity_info = user_entity.telegram_entity
    #                         entities_list.append(
    #                             {
    #                                 "entity_id": entity_info.id,
    #                                 "entity_name": entity_info.entity_name,
    #                                 "entity_type": entity_info.entity_type,
    #                             }
    #                         )
    #                     if len(entities_list):
    #                         entities_types = list(set(e.get("entity_type") for e in entities_list))
    #                     content = {
    #                         "entities_types": entities_types,
    #                         "options": entities_list
    #                     }
    #                     response = render(request, self.template_name, content)
    #                     return response
    #                 _user_telegram_session.is_verified = False
    #                 _user_telegram_session.save()                    
    #         return redirect('telegram:authentication')
    #     except Exception as e:
    #         _error = f"error - {e}"
    #         return render(request, "500.html", context={"exception": f"Error - {_error}"})

    # def get(self, request, *args, **kwargs):
    #     try:
    #         user_id = request.user.id
    #         phone_number_object = request.user.telegram_phone_number
    #         _user_telegram_session = TelethonSession.objects.filter(owner_id=user_id, phone_number=phone_number_object).first()
    #         if _user_telegram_session is not None:
    #             _is_verified = _user_telegram_session.is_verified
    #             if _is_verified:
    #                 _session_data = _user_telegram_session.session_data
    #                 data_returning = async_to_sync(session_validation)(_session_data)
    #                 _is_valid_session = data_returning.get("is_valid")
    #                 if _is_valid_session:
    #                     user_entities_data = async_to_sync(telethon_user_entities)(_session_data)
    #                     print(f"(func) UserTelegramEntitiesView : {user_entities_data}")
    #                     entities_list = user_entities_data.get("entities",[])
    #                     context = {
    #                         # "entities": _recorded_user_entities
    #                         "entities_types": ["User", "Chat", "Channel"],
    #                         "options": entities_list
    #                     }
                        # response = render(request, self.template_name, context)
                        # celery_task_id = request.COOKIES.get("celery_task_id")
                        # # celery_task_id = None
                        # if celery_task_id:
                        #     if not AsyncResult(celery_task_id).ready(): # no new task will assign unless the status is SUCCESS or FAILURE
                        #         context = {
                        #             # "entities": _recorded_user_entities
                        #             "entities_types": ["User", "Chat", "Channel", f"Ready - {AsyncResult(celery_task_id).ready()}", f"Result - {AsyncResult(celery_task_id).result}", f"status - {AsyncResult(celery_task_id).status}"],
                        #             "options": entities_list
                        #         }
                        #         response = render(request, self.template_name, context)
                        #         return response
                        # celery_task_id = celery_testing.delay(_session_data)
                        # response.set_cookie(
                        #     "celery_task_id",
                        #     celery_task_id,

telegram_content_scrapper/telegram_content_scrapper/users/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin
from rest_framework.mixins import RetrieveModelMixin
from rest_framework.mixins import UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from telegram_content_scrapper.users.models import User

from .serializers import UserSerializer


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

telegram_content_scrapper/telegram_content_scrapper/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from telegram_content_scrapper.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    # fields = ["name"]
    fields = ["telegram_phone_number"]
    # fields = ["name", "telegram_phone_number"]
    success_message = _("Information successfully updated")

    def get_success_url(self) -> str:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user.get_absolute_url()

    def get_object(self, queryset: QuerySet | None=None) -> User:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self) -> str:
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()



@login_required
def logout_delete_cookie_data(request):
    try:
        response = redirect('account_logout')
        for cookie_name in request.COOKIES:
            response.delete_cookie(cookie_name)
        return response
    except Exception as e:
        err_found = f"error - {e}"
        return render(request, "500.html", context={"exception": f"Error - {err_found}"})

telegram_content_scrapper/telegram_content_scrapper/templates/telegram_scrapper/telegram_authentication.html
{% extends "../base.html" %}
{% load static %}
{% block content %}
    <h1 class="text-center custom-h1">Get User's Telegram Account Session through Authentication</h1>
    <br>
    <div class="card d-flex justify-content-center align-items-center">
        <div class="card-body text-center">
            <h2 class="card-title">OTP Verification</h2>
            <img class="img-fluid" style="max-width:min(30vw, 100px);height: auto;" src="{% static 'images/icons/secure-icon.jpg' %}" alt="OTP verification">
            <div id="process-state-caption" class="otp-process-state-cap">
                {% if msg_need_attention %}
                    {% for message in messages %}
                        <p class="card-text same-group-p text-danger">{{ message }}</p>
                    {% endfor %}
                {% else %}
                    <p class="card-text same-group-p">{{ loading_msg }} 
                        <span class="loading-dots">
                            <span></span><span></span><span></span><span></span>
                        </span>
                    </p>
                {% endif %}
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    {{ form.code }}
                </div>
                <button class="btn btn-primary" type="submit">Verify OTP Code</button>
            </form>
        </div>
            <p>Didn't receive OTP code. 
                <b><a href="#" class="text-primary" onclick="resendOtpCode()">Resend Code</a></b> or
                <b><a href="{% url 'users:update' %}" class="text-primary">Update Phone Number</a></b>
            </p>
            <p>If still didn't get OTP code, make sure Two-Step Verification is Off.</p>
    </div>
    <script>
        let is_data_loaded = {{ is_data_loaded|yesno:"true,false" }};
        let is_data_loading = false;
        let loading_msg = `{{ loading_msg|default:''|escapejs }}`;

        const API_ENDPOINT = "{% url 'telegram:send-otp' %}";

        // Function to load data
        async function sendOtpCode() {
            let otpInput = document.querySelector("input[name='code']");  // Selects the OTP input field
            if (otpInput) {
                otpInput.value = "";  // Clear input field on page load
            }
            is_data_loading = true;
            if (is_data_loading) {
                console.log("Loading msg -", loading_msg)
                let div = document.getElementById("process-state-caption");
                div.innerHTML = `<p class="card-text same-group-p">${loading_msg} 
                        <span class="loading-dots">
                            <span></span><span></span><span></span><span></span>
                        </span>
                    </p>`;
            }

            try {
                let response = await fetch(API_ENDPOINT, {
                    method: 'GET',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    }
                });
                let result = await response.json();
                console.log(result);
                loading_msg = result.data.loading_msg || "Default loading message";
                displayData(result.data);
                
                is_data_loaded = true;
            } catch (error) {
                console.error("Error fetching data:", error);
            } finally {
                is_data_loading = false;
            }
        }

        // Function to reload data
        async function resendOtpCode() {
            if (!is_data_loading) {
                sendOtpCode();
            }
        }

        // Function to display data
        function displayData(data) {
            let div = document.getElementById("process-state-caption");
            console.log(data);
            div.innerHTML = "";
            if (data.is_successed) {
                data.messages.forEach(message => {
                    let row = `<p class="card-text same-group-p text-success">${message}</p>`;
                    div.innerHTML += row;
                });
            } else {
                data.messages.forEach(message => {
                    let row = `<p class="card-text same-group-p text-danger">${message}</p>`;
                    div.innerHTML += row;
                });
            }
            
            console.log(div.innerHTML);
        }

        // Load data when the page loads
        window.onload = function() {
            if (!is_data_loaded && !is_data_loading) {
                sendOtpCode();
            }
        };
    </script>
{% comment %}     
    <script>
    $(document).ready(function() {
        $('#resend-code-button').click(function() {
        // Submit the form again to resend the code
        $('#verification-code-form').submit();
        });
    });
    </script> {% endcomment %}
{% endblock content %}